<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>run.output</string>
        <key>name</key>
        <string>run-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>\b(Finished)\b</string>
                <key>name</key>
                <string>comment</string>
            </dict>
            <dict>
                <key>match</key>
                <string>([\(\)\-\*\/\<\>])</string>
                <key>name</key>
                <string>token.error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(note|hint|info|information|Running))\b</string>
                <key>name</key>
                <string>token.info-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(Warning|warn))\b</string>
                <key>name</key>
                <string>token.warn-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(Error|Failure|Fail|failed|timeout|Exited))\b</string>
                <key>name</key>
                <string>token.error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b((Compiling)|(0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
                <key>name</key>
                <string>token.debug-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>("(([a-zA-Z]:)|(\\\\[^/\\:\*\?""<>\|]+(\\[a-zA-Z]\$)?))\\([^/\\:\*\?""<>\|]+\\)*[^/\\:\*\?""<>\|]+(\.[^/\\:\*\?""<>\|]+[^/\\:\*\?""<>\|\s])?")|((([a-zA-Z]:)|(\\\\[^/\\:\*\?""<>\|\s]+(\\[a-zA-Z]\$)?))\\([^/\\:\*\?""<>\|\s]+\\)*[^/\\:\*\?""<>\|\s]+(\.[a-zA-Z0-9]+)?)</string>
                <key>name</key>
                <string>string</string>
            </dict>
        </array>
    </dict>
</plist>